version: '3.8'

services:
  flask-ml-service:
    build: .
    ports:
      - "5000:5000"
    networks:
      - backend
    depends_on:
      - discovery-server

  discovery-server:
    image: eurekaserver:latest
    ports:
      - "8761:8761"
    networks:
      - backend

networks:
  backend:
